name: Deploy Firebase Rules

on:
  push:
    branches:
      - main
    paths:
      - firestore.rules
      - firestore.indexes.json
      - database.rules.json

jobs:
  deploy:
    name: Deploy rules to Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy Firestore & RTDB rules
        run: firebase deploy --only firestore:rules,firestore:indexes,database --project doodle-canvas-b3ddb --token ${{ secrets.FIREBASE_TOKEN }}
